"""
BACQE Convex Survival research platform.

This package provides ingestion, validation, attribution and research
management tools for evidence generated by the BACQE Convex Survival
MQL5 execution engine.
"""